apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: keycloakdb
spec:
  image: us.gcr.io/container-suite/crunchy-postgres-ha:ubi8-13.2-ci-latest
  openshift: true
  port: 5432
  postgresVersion: 13
  instances:
    - name: 'pgc'
      replicas: 2
      resources:
        limits:
          cpu: 1.0
          memory: 1Gi
      volumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi

  archive:
    pgbackrest:
      image: us.gcr.io/container-suite/crunchy-pgbackrest:ubi8-13.2-ci-latest
      repoHost:
        dedicated: {}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            storageClassName: "standard"
            resources:
              requests:
                storage: 10Gi

