apiVersion: v1
kind: Service
metadata:
  name: findev-lb
  namespace: finance
spec:
  selector:
    postgres-operator.crunchydata.com/role: master
    postgres-operator.crunchydata.com/cluster: findev
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
